version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.11

    steps:
      - checkout

      - run:
          name: Install packages
          command: npm install

      - run:
          name: Run test
          command: npm test

workflows:
  version: 2

  test-workflow:
    jobs:
      - test